#!/bin/bash
cd /etc
sudo rm -rf os-release && sudo rm -rf gentoo-release
sudo wget https://raw.githubusercontent.com/orchid-linux/orchid/main/testing/gentoo-release &> /dev/null
sudo wget https://raw.githubusercontent.com/orchid-linux/orchid/main/testing/os-release &> /dev/null
